INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (1, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (1, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (2, 'a) physical')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (2, 'b) logical')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (2, 'c) user')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (2, 'd) view')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (3, 'a) physical')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (3, 'b) logical')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (3, 'c) user')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (3, 'd) view')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (4, 'a) Schema')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (4, 'b) Attribute')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (4, 'c) Parameter')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (4, 'd) Instance')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (5, 'a) Schema')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (5, 'b) Attribute')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (5, 'c) Parameter')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (5, 'd) Instance')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (6, 'a) ER')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (6, 'b) Network')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (6, 'c) Semantic')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (6, 'd) Functional')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (7, 'a) physical')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (7, 'b) logical')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (7, 'c) user')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (7, 'd) view')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (8, 'a) Only 1')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (8, 'b) Only 2')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (8, 'c) Both 1 and 2 individually')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (8, 'd) Either 1 or 2')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (9, 'a) Begin transaction and end transaction')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (9, 'b) Start transaction and stop transaction')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (9, 'c) Get transaction and post transactio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (9, 'd) Read transaction and write transactio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (10, 'a) Atomicity')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (10, 'b) Durability')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (10, 'c) Isolatio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (10, 'd) All of the mentioned')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (11, 'a) Atomicity')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (11, 'b) Durability')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (11, 'c) Isolatio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (11, 'd) All of the mentioned')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (12, 'a) Atomicity')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (12, 'b) Durability')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (12, 'c) Isolatio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (12, 'd) All of the mentioned')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (13, 'a) Producing detail summary or exception reports')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (13, 'b) Recording a business activity')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (13, 'c) Confirming an action or triggering a response')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (13, 'd) Maintaining a data')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (14, 'a) Consistency')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (14, 'b) Atomicity')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (14, 'c) Durability')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (14, 'd) Isolatio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (15, 'a) implicit locks')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (15, 'b) explicit locks ')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (15, 'c) exclusive locks')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (15, 'd) shared locks')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (16, 'a) Implicit lock')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (16, 'b) Explicit lock')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (16, 'c) Exclusive lock')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (16, 'd) Shared lock')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (17, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (17, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (18, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (18, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (19, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (19, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (20, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (20, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (21, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (21, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (22, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (22, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (23, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (23, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (24, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (24, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (25, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (25, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (26, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (26, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (27, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (27, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (28, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (28, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (29, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (29, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (30, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (30, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (31, 'a) dynamic conditio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (31, 'b) race condition')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (31, 'c) essential condition')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (31, 'd) critical condition')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (32, 'a) mutual exclusio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (32, 'b) critical exclusion')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (32, 'c) synchronous exclusion')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (32, 'd) asynchronous exclusion')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (33, 'a) thread')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (33, 'b) pipe')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (33, 'c) semaphore')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (33, 'd) socket')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (34, 'a) that cannot drop below zero')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (34, 'b) that cannot be more than zero')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (34, 'c) that cannot drop below one')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (34, 'd) that cannot be more than one')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (35, 'a) mutex locks')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (35, 'b) binary semaphores')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (35, 'c) both mutex locks and binary semaphores')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (35, 'd) none of the mentioned')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (36, 'a) hardware level')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (36, 'b) software level')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (36, 'c) both hardware and software level')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (36, 'd) none of the mentioned')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (37, 'a) shared data structures')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (37, 'b) procedures that operate on shared data structure')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (37, 'c) synchronization between concurrent procedure invocatio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (37, 'd) all of the mentioned')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (38, 'a) a condition variable must be declared as conditio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (38, 'b) condition variables must be used as Boolean objects')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (38, 'c) semaphore must be used')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (38, 'd) all of the mentioned')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (39, 'a) data consistency')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (39, 'b) data insecurity')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (39, 'c) data inconsistency')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (39, 'd) none of the mentioned')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (40, 'a) data consistency')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (40, 'b) race conditio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (40, 'c) aging')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (40, 'd) starvatio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (41, 'a) program')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (41, 'b) critical sectio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (41, 'c) non – critical sectio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (41, 'd) synchronizing')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (42, 'a) Mutual Exclusio')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (42, 'b) Progress')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (42, 'c) Bounded Waiting')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (42, 'd) All of the mentioned')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (43, 'a) after a particular process')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (43, 'b) periodically')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (43, 'c) atomically')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (43, 'd) none of the mentioned')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (44, 'a) wait')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (44, 'b) stop')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (44, 'c) hold')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (44, 'd) none of the mentioned')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (45, 'a) one')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (45, 'b) two')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (45, 'c) three')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (45, 'd) four')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (46, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (46, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (47, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (47, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (48, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (48, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (49, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (49, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (50, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (50, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (51, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (51, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (52, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (52, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (53, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (53, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (54, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (54, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (55, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (55, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (56, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (56, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (57, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (57, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (58, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (58, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (59, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (59, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (60, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (60, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (61, 'a. Structured analysis')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (61, 'b. Structured design.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (61, 'c. Structured programming.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (61, 'd. All the previous.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (62, 'a. Structured approach.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (62, 'b. Structured program.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (63, 'a. Structured approach.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (63, 'b. Structured program.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (64, 'a. Object-oriented.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (64, 'b. Structured.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (65, 'a. Object-oriented analysis (OOA).')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (65, 'b. Object-oriented design (OOD)')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (65, 'c. Object-oriented programming (OOP).')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (66, 'a. Object-oriented analysis (OOA).')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (66, 'b. Object-oriented design (OOD).')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (66, 'c. Object-oriented programming (OOP).')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (67, 'a. Object-oriented analysis (OOA).')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (67, 'b. Object-oriented design (OOD).')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (67, 'c. Object-oriented programming (OOP).')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (68, 'a. ERDs.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (68, 'b. DFDs.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (68, 'c. FDCs.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (68, 'd. All the previous.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (69, 'a. Use case diagrams.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (69, 'b. Class diagrams.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (69, 'c. Both.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (70, 'a. Tables (relations).')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (70, 'b. Columns (attributes) ')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (70, 'c. Primary & foreign keys')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (70, 'd. All the previous.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (71, 'a. Object definition language (ODL).')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (71, 'b. ERD.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (71, 'c. DFD.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (72, 'a. Files.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (72, 'b. Records.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (72, 'c. Fields.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (72, 'd. Pointers.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (73, 'a. Class definitions.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (73, 'b. Tables.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (73, 'c. Columns.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (74, 'a. Requirement.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (74, 'b. Files')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (74, 'c. Fields.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (75, 'a. General requirements.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (75, 'b. Functional requirements.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (75, 'c. Data requirements.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (75, 'd. Implementation requirements.')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (76, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (76, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (77, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (77, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (78, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (78, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (79, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (79, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (80, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (80, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (81, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (81, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (82, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (82, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (83, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (83, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (84, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (84, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (85, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (85, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (86, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (86, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (87, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (87, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (88, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (88, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (89, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (89, 'true')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (90, 'false')
INSERT [dbo].[Question_Choices] ([ques_id], [choice]) VALUES (90, 'true')
